# Generated by Django 4.2.14 on 2024-08-09 07:13

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_image_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/default.png', upload_to='profile/', validators=[accounts.validators.validate_image_extension, accounts.validators.validate_image_size]),
        ),
    ]
