# Generated by Django 4.2.14 on 2024-08-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productimagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductCategoryModel',
        ),
    ]
