# Generated by Django 4.2.14 on 2024-08-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_productcategory_productcategorymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='discount_precent',
            new_name='discount_percent',
        ),
    ]
