# Generated by Django 4.2.14 on 2024-08-09 19:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productmodel_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='breif_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
