# Generated by Django 4.2.14 on 2024-08-10 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_addressusermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='street',
            new_name='city',
        ),
        migrations.AddField(
            model_name='addressusermodel',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
