# Generated by Django 4.2.14 on 2024-08-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentmodel_authority_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='card_pan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
