# Generated by Django 4.2.14 on 2024-08-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='craeted_date',
            new_name='created',
        ),
    ]
