# Generated by Django 4.2.14 on 2024-08-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_craeted_date_reviewmodel_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='created',
            new_name='created_date',
        ),
    ]
